version: '3'
services:
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/hr-management
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
